tarantool/grafana-dashboard

- example/project/app/roles/custom.lua
- example/project/init.lua
- example/project/project-scm-1.rockspec
> metrics: upgrade to 0.3.0 version

- docker-compose.yml
> Fix alias in example project

- README.md
Update README due to https://github.com/tarantool/grafana-dashboard/issues/2#issuecomment-675161265 suggestion
> Explicitly refer to Grafana page for Tarantool setup instructions

- CHANGELOG.md
- docker-compose.yml
- example/project/.luacheckrc
- example/project/Dockerfile
- example/project/app/roles/custom.lua
- example/project/cluster/helper.lua
- example/project/cluster/init.lua
- example/project/cluster/integration/bootstrap_test.lua
- example/project/init.lua
- example/prometheus/prometheus.yml
- example/telegraf/telegraf.conf
Closes #20 
Start a cluster of Tarantools in docker example instead of a single instance with luatest.
Generate some traffic for HTTP and space panels with luatest.
> Start a cluster of Tarantools in docker example

- CHANGELOG.md
- tarantool/cluster.libsonnet
- tarantool/dashboard.libsonnet
- tarantool/prometheus_dashboard.jsonnet
- tests/Prometheus/dashboard_compiled.json
> Cluster overview panels for Prometheus

- .github/workflows/main.yml
- Makefile
- tests.sh
> Add tests CI

- CHANGELOG.md
- example/prometheus/alerts.yml
- example/prometheus/test_alerts.yml
- tarantool/cluster.libsonnet
- tarantool/dashboard.libsonnet
- tarantool/influxdb_dashboard.jsonnet
- tarantool/prometheus_dashboard.jsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/Prometheus/dashboard_compiled.json
> Add Cartridge issues panels and Prometheus alerts

- CHANGELOG.md
- tarantool/dashboard.libsonnet
- tarantool/net.libsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/Prometheus/dashboard_compiled.json
> Add network panels

- CHANGELOG.md
- tarantool/cpu.libsonnet
- tarantool/dashboard.libsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/Prometheus/dashboard_compiled.json
> Add CPU time getrusage panels

- CHANGELOG.md
- example/prometheus/alerts.yml
- example/prometheus/test_alerts.yml
- tarantool/cluster.libsonnet
- tarantool/dashboard.libsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/Prometheus/dashboard_compiled.json
> Add replication lag panel

- README.md
> Make screenshots fit in one row

- CHANGELOG.md
- dashboard/panels/cpu.libsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/InfluxDB/dashboard_with_custom_panels_compiled.json
- tests/Prometheus/dashboard_compiled.json
- tests/Prometheus/dashboard_with_custom_panels_compiled.json
> Show CPU time in percents

- CHANGELOG.md
> Release 0.3.2

- CHANGELOG.md
- dashboard/panels/cluster.libsonnet
- tests/Prometheus/dashboard_compiled.json
- tests/Prometheus/dashboard_with_custom_panels_compiled.json
> Use green color for low values in overall panels

- CHANGELOG.md
- example/project/app/roles/custom.lua
> Configure default collector in example cluster

- README.md
- example/project/app.Dockerfile
> Fix mixing tabs and spaces in README and Dockerfile

- CHANGELOG.md
- dashboard/panels/cluster.libsonnet
- tests/Prometheus/dashboard_compiled.json
- tests/Prometheus/dashboard_with_custom_panels_compiled.json
> Make variables comparison consistent in Prometheus dashboard

- README.md
> Fix README json comment

- CHANGELOG.md
- dashboard/influxdb_dashboard.libsonnet
- dashboard/panels/cluster.libsonnet
- dashboard/panels/common.libsonnet
- dashboard/panels/cpu.libsonnet
- dashboard/panels/http.libsonnet
- dashboard/panels/net.libsonnet
- dashboard/panels/operations.libsonnet
- dashboard/panels/runtime.libsonnet
- dashboard/panels/space.libsonnet
- dashboard/panels/vinyl.libsonnet
- dashboard/prometheus_dashboard.libsonnet
- dashboard/section.libsonnet
- example_cluster/project/app/roles/custom.lua
- example_cluster/project/project-scm-1.rockspec
- tests/InfluxDB/dashboard_compiled.json
- tests/InfluxDB/dashboard_with_custom_panels_compiled.json
- tests/Prometheus/dashboard_compiled.json
- tests/Prometheus/dashboard_with_custom_panels_compiled.json
> Add space tuples number and bsize panels

- README.md
> readme: add link to grafonnet tutorial

- doc/monitoring/grafana_dashboard.rst
> doc: add CRUD statistics requirements

- .github/workflows/main.yml
- .gitignore
- Makefile
- doc/monitoring/grafana_dashboard.rst
- tests.sh
Fix grammar error in entry. Change error message style.
Add troubleshooting tip related to error [1] .
1. https://github.com/grafana/grafana/issues/44542
> doc: update troubleshooting info

- doc/monitoring/grafana_dashboard.rst
> doc: bump metrics requirement

- .github/pull_request_template.md
Add missing doc/README update advises.
If this pull request introduces support for new metrics, do not forget to
- add Grafana panel;
- run `make update-tests` to build new dashboard artifacts;
- add example application code to generate non-null metrics;
- attach a screenshot of a new panel to the PR description;
- add new Telegraf tag key, if relevant,
- to all `telegraf.conf` files,
- to "Grafana dashboard" documentation page;
- add alert example, if relevant,
- to `alerts.yml`,
- to "Alerting" documentation page;
- update `supported_metrics.md`.
In any case, do not forget to
- link an issue,
- add a CHANGELOG entry.
> github: update pull request template

- CHANGELOG.md
- dashboard/build/influxdb/dashboard.libsonnet
- dashboard/build/influxdb/dashboard_static.jsonnet
- dashboard/build/influxdb/tdg_dashboard.libsonnet
- dashboard/build/influxdb/tdg_dashboard_raw.libsonnet
- dashboard/build/influxdb/tdg_dashboard_static.jsonnet
- dashboard/panels/cluster.libsonnet
- dashboard/panels/cpu.libsonnet
- dashboard/panels/crud.libsonnet
- dashboard/panels/tdg/graphql.libsonnet
- dashboard/panels/tdg/tasks.libsonnet
- dashboard/panels/tdg/tuples.libsonnet
- tests/InfluxDB/dashboard_compiled.json
- tests/InfluxDB/dashboard_tdg_compiled.json
- tests/InfluxDB/dashboard_tdg_static_compiled.json
- tests/InfluxDB/dashboard_tdg_static_custom_title_compiled.json
- tests/InfluxDB/dashboard_tdg_static_with_instance_variable_compiled.json
- tests/InfluxDB/dashboard_with_custom_panels_compiled.json
- tests/Prometheus/dashboard_compiled.json
- tests/Prometheus/dashboard_static_compiled.json
- tests/Prometheus/dashboard_static_custom_title_compiled.json
- tests/Prometheus/dashboard_static_with_instance_variable_compiled.json
- tests/Prometheus/dashboard_tdg_compiled.json
- tests/Prometheus/dashboard_tdg_static_compiled.json
- tests/Prometheus/dashboard_tdg_static_custom_title_compiled.json
- tests/Prometheus/dashboard_tdg_static_with_instance_variable_compiled.json
- tests/Prometheus/dashboard_with_custom_panels_compiled.json
This PR introduces several bugfixes which I had met while solveing #204, #206, #207. See commit messages for more info.
> Various bugfixes

- CHANGELOG.md
- dashboard/panels/tdg/tasks.libsonnet
- tests/Prometheus/dashboard_tdg_compiled.json
- tests/Prometheus/dashboard_tdg_static_compiled.json
- tests/Prometheus/dashboard_tdg_static_custom_title_compiled.json
- tests/Prometheus/dashboard_tdg_static_with_instance_variable_compiled.json
> Remove extra quotation at the end of TDG jobs_average_panel query
