tarantool/grafana-dashboard

README.md

Closes #3
Add dashboard to Grafana Official & community built dashboards. Rework README to describe import from Grafana Official & community built dashboards, separate build section cause it is not a obligatory stage for using dashboard now.

Add dashboard to Grafana community built dashboards

---

CHANGELOG.md
example/project/cluster/integration/bootstrap_test.lua

Fix example cluster start

---

CHANGELOG.md
example/project/app/roles/custom.lua
example/project/project-scm-1.rockspec
example/telegraf/telegraf.conf
tarantool/http.libsonnet
tests/InfluxDB/dashboard_compiled.json

Update metrics version to 0.5.0.
Replace average latency collector with summary collector in example cluster.
Example cluster metrics no more breaks Prometheus metrics collect (closes #13).
Replace average latency panels with summary 99th percentile panels (closes #29).

Replace average collector with summary collector

---

CHANGELOG.md
README.md
tarantool/dashboard.libsonnet
tarantool/http.libsonnet
tarantool/influxdb_dashboard.jsonnet
tarantool/prometheus_dashboard.jsonnet
tarantool/slab.libsonnet
tarantool/space.libsonnet
tests/InfluxDB/dashboard.jsonnet
tests/Prometheus/dashboard.jsonnet
tests/Prometheus/dashboard_compiled.json

Rework code to support both InfluxDB and Prometheus targets.
Add Prometheus dashboard (closes #14).
Clean up code (closes #24).

Prometheus dashboard

---

CHANGELOG.md
README.md
example/prometheus/prometheus.yml
tarantool/cluster.libsonnet
tarantool/dashboard.libsonnet
tarantool/http.libsonnet
tarantool/prometheus_dashboard.jsonnet
tarantool/space.libsonnet
tests/Prometheus/dashboard_compiled.json

Closes #46
Change example container Prometheus scrape time. Make Prometheus rps graphs rate() time range configurable both on import and in the runtime.
Configure on import:
Configure in runtime:
1. Change current constant variable value. Assumes that user use default scrape time or scrape time less than default. If this assumption is not correct, it would be inconvenient to set acceptable value to "fix" the board.
2. Set variable only on import (with default variable value '2m'). If user would ignore setting parameter on import, it would be also inconvenient to change acceptable value to "fix" the board.
3. Set variable only in runtime (with default variable value '2m'). I think it's better to be able to set value also on import than not.
4. Use `$__interval`. It doesn't work.
5. Use …

Make Prometheus rps graphs rate() time range configurable

---

.github/workflows/main.yml
CHANGELOG.md
Makefile
docker-compose.yml
example/prometheus/alerts.yml
example/prometheus/prometheus.yml
example/prometheus/test_alerts.yml

Closes #43 
Added Prometheus example alert rules:
- instance state (Prometheus `up`),
- Lua memory (warning and alert),
- arena/items limit warnings and alerts,
- high HTTP latency,
- too many HTTP 4xx responses (on a single instance or overall on cluster),
- HTTP 5xx errors,
- low router HTTP activity.
Alerts are separated into three groups. `common` is non-Tarantool alert on process work (Prometheus `up`). `tarantool-common` are general Tarantool alerts (Lua memory and slab_ratio) that can be applied to any Tarantool application. `tarantool-business` is a list of references on how you can monitor your business logic. One can base its alert rules on what's described there (because it's impossible to say if it is OK for your app to have 1000 RPS of 4xx errors or 0 requests on a router for …

Prometheus example alert rules

---

CHANGELOG.md
doc/monitoring/grafana_dashboard.rst
example/project/Dockerfile
example/project/project-scm-1.rockspec
example/telegraf/telegraf.conf

Closes #58 
Update metrics and cartridge packages version.
Add missing space replication and cartridge issues metrics labels to Telegraf configuration

Add missing metrics label tags to Telegraf configuration

---

CHANGELOG.md
dashboard/cluster.libsonnet
dashboard/common.libsonnet
dashboard/cpu.libsonnet
dashboard/http.libsonnet
dashboard/influxdb_dashboard.jsonnet
dashboard/memory_misc.libsonnet
dashboard/net.libsonnet
dashboard/operations.libsonnet
dashboard/prometheus_dashboard.jsonnet
dashboard/slab.libsonnet
dashboard/vinyl.libsonnet
example/project/app/roles/custom.lua
example/project/generate_load.lua
example/prometheus/alerts.yml
example/prometheus/test_alerts.yml
tests/InfluxDB/dashboard_compiled.json
tests/Prometheus/dashboard_compiled.json

Code rework: use common graph template to reduce code copypaste, set panel size in code.
Rename "Tarantool memory allocation overview" to "Tarantool memtx allocation overview".
Add vinyl panels and alert examples (closes #86).

Vinyl metrics

---

example/project/app.Dockerfile

https://github.com/tarantool/grafana-dashboard/blob/c5fd7a811903326d1a7cdb192219db3992d404b9/example/project/app.Dockerfile#L14
Docker executes these commands using the `/bin/sh -c` interpreter, which only evaluates the exit code of the last operation in the pipe to determine success. 
In this build step succeeds and a next step is broke if the `curl` command fails. 
Based on the error received, the problem will not be obvious because the next step will fail, not the current step.
Solution taken from [docker documentation](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) (Using pipes).

Add pipefail to the bash pipeline in the app.Dockerfile.

---

CHANGELOG.md
README.md
docker-compose.localapp.yml
example/prometheus/prometheus.localapp.yml
example/telegraf/telegraf.localapp.conf

Add Telegraf+InfluxDB+Prometheus+Grafana cluster for local Tarantool Cartridge app monitoring and short configuration guide.

Cluster for local Tarantool app monitoring

---

.github/workflows/pull-translation.yml
.github/workflows/push-translation.yml
.github/workflows/upload-translations.yml

Docs don't build with Python v.3.10 (it's the default version in CI)
- https://github.com/tarantool/cartridge-cli/runs/3994597525?check_suite_focus=true
- https://github.com/tarantool/metrics/actions/runs/1399714133

Update python versions in CI

---

CHANGELOG.md
dashboard/dashboard.libsonnet
dashboard/panels/common.libsonnet
dashboard/utils.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

After this patch, all dashboards will be built with collapsed rows. User
could uncollapse rows he is interested with and save dashboard with
common Grafana tools. The change will drastically increase performance
on dashboard load, especially for big Tarantool clusters.
Closes #128

Collapse dashboard rows

---

CHANGELOG.md
dashboard/panels/runtime.libsonnet
dashboard/section.libsonnet
example_cluster/project/project-scm-1.rockspec
example_cluster/prometheus/alerts.yml
example_cluster/prometheus/test_alerts.yml
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Bump metrics to 0.13.0 to test panels for event loop metrics.
See metrics CHANGELOG [1] for other updates.
1. https://github.com/tarantool/metrics/blob/master/CHANGELOG.md
Follows up #72
Closes #73

dashboard: add event loop panel and alerts

---

CHANGELOG.md
dashboard/influxdb_dashboard.libsonnet
dashboard/panels/luajit.libsonnet
dashboard/prometheus_dashboard.libsonnet
dashboard/section.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Add panels for the following LuaJit metrics:
- lj_jit_snap_restore
- lj_jit_trace_num
- lj_jit_trace_abort
- lj_jit_mcode_size
- lj_strhash_hit
- lj_strhash_miss
- lj_gc_steps_atomic
- lj_gc_steps_sweepstring
- lj_gc_steps_finalize
- lj_gc_steps_sweep
- lj_gc_steps_propagate
- lj_gc_steps_pause
- lj_gc_strnum
- lj_gc_tabnum
- lj_gc_cdatanum
- lj_gc_udatanum
- lj_gc_freed
- lj_gc_memory
- lj_gc_allocated
LuaJit metrics were introduced in Tarantool 2.6 and metrics 0.6.0
Closes #75

dashboard: add panels for LuaJit metrics

---

CHANGELOG.md
dashboard/panels/net.libsonnet
dashboard/panels/runtime.libsonnet
dashboard/panels/vinyl.libsonnet
dashboard/section.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Add a panel for tnt_info_memory_tx metrics
to "Tarantool runtime overview" section.
Add panels for tnt_info_memory_net and tnt_net_connections_total
metrics to "Tarantool network activity" section. Rework some current
"Tarantool network activity" panels to be more consistent with new
panels.
Add panels for tnt_vinyl_memory_page_index and
tnt_vinyl_memory_bloom_filter metrics to "Tarantool vinyl statistics"
section.
Closes #137

Lost & Found panels

---

CHANGELOG.md
README.md
dashboard/influxdb_dashboard.libsonnet
dashboard/panels/common.libsonnet
dashboard/panels/crud.libsonnet
dashboard/prometheus_dashboard.libsonnet
dashboard/section.libsonnet
example_cluster/project/app/roles/custom.lua
example_cluster/project/app/roles/router.lua
example_cluster/project/app/roles/storage.lua
example_cluster/project/generate_load.lua
example_cluster/project/init.lua
example_cluster/project/project-scm-1.rockspec
example_cluster/project/replicasets.yml
example_cluster/prometheus/alerts.yml
example_cluster/prometheus/test_alerts.yml
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Add CRUD rocks 0.11.1 to example application dependency list. Add
loaders for CRUD methods to generate_load script.
`default` InfluxDB policy keyword cannot be used as a value in raw
InfluxDB queries. `autogen` retention policy is created by default [1]:
> When you create a database, InfluxDB automatically creates a retention
> policy called autogen with an infinite duration, a replication factor
> set to one, and a shard group duration set to seven days
thus it is well-suited to be a default value.
1. https://www.influxdata.com/blog/simplifying-influxdb-retention-policy-best-practices/
Statistics for CRUD module was introduced in CRUD 0.11.0 [1].
To enable statistics integrated with metrics with quantiles, call
```lua
crud.cfg{
stats = true,
stats_driver = 'metrics',
stats_quantiles = …
```

Add CRUD panels

---

CHANGELOG.md
dashboard/panels/cluster.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Change replication status "slave" labels to "replica" to be consistent
with documentation.
Follows up #133

dashboard: change replication status panel labels

---

CHANGELOG.md
dashboard/panels/runtime.libsonnet
dashboard/section.libsonnet
example_cluster/prometheus/alerts.yml
example_cluster/prometheus/test_alerts.yml
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

tnt_fiber_csw is not a monotonic metric since it summarize context
switches over all current fibers. If fiber is already dead, its share
is no more included. Thus, using rate on tnt_fiber_csw is incorrect.
Using rate with tnt_fiber_csw metric is incorrect.
Follows up #72

Fix context switches monitoring

---

CHANGELOG.md
README.md
doc/monitoring/grafana_dashboard.rst
example_cluster/project/app.Dockerfile

Grafana revisions:
- InfluxDB revision 12 [1]
- Prometheus revision 12 [2]
- InfluxDB TDG revision 1 [3]
- Prometheus TDG revision 1 [4]
Added:
- TDG (ver. 2) example cluster draft
- Dashboard templates for TDG (ver. 2)
- Kafka metrics panels for TDG dashboard
- Thread CPU panels for TDG dashboard
- expirationd panels for TDG dashboard
- Tuples panels for TDG dashboard
- File connectors panels for TDG dashboard
- GraphQL requests panels for TDG dashboard
- IProto requests panels for TDG dashboard
- REST API requests panels for TDG dashboard
- Task statistics panels for TDG dashboard
Changed:
- Change replication status panel labels
Fixed:
- Remove rate from fiber context switches panel
- Remove fiber context switches alert example
1. …

Release 1.2.0

---

CHANGELOG.md
dashboard/panels/tdg/file_connectors.libsonnet
tests/InfluxDB/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json

Change TDG file connectors panel name from "Total iles processed" to
"Total files processed".
Closes #157

tdg_dashboard: fix panel name typo

---

CHANGELOG.md
dashboard/panels/tdg/kafka/topics.libsonnet
tests/InfluxDB/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json

Fix metrics name for "TDG Kafka topics statistics" panels:
- "Partition messages sent"
(tdg_kafka_topic_partitions_txmsgs),
- "Partition message bytes sent"
(tdg_kafka_topic_partitions_txbytes),
- "Partition messages consumed"
(tdg_kafka_topic_partitions_rxmsgs),
- "Partition message bytes consumed"
(tdg_kafka_topic_partitions_rxbytes),
- "Partition messages dropped"
(tdg_kafka_topic_partitions_rx_ver_drops),
- "Partition messages in flight"
(tdg_kafka_topic_partitions_msgs_inflight).
Closes #155

tdg_dashboard: fix Kafka partitions metrics

---

CHANGELOG.md
dashboard/panels/tdg/kafka/brokers.libsonnet
dashboard/panels/tdg/kafka/topics.libsonnet
tests/Prometheus/dashboard_tdg_compiled.json

Display only 99th quantile for Prometheus TDG Kafka metrics:
- "TDG Kafka brokers statistics" panels:
- "Producer queue latency" (tdg_kafka_broker_int_latency),
- "Request queue latency" (tdg_kafka_broker_outbuf_latency),
- "Broker latency" (tdg_kafka_broker_rtt),
- "Broker throttle" (tdg_kafka_broker_throttle);
- "TDG Kafka topics statistics" panels:
- "Batch size" (tdg_kafka_topic_batchsize),
- "Batch message count" (tdg_kafka_topic_batchcnt).
Closes #156

tdg_dashboard: display only 99th quantile

---

CHANGELOG.md

Grafana revisions: [InfluxDB revision 12](https://grafana.com/api/dashboards/12567/revisions/12/download), [Prometheus revision 12](https://grafana.com/api/dashboards/13054/revisions/12/download), [InfluxDB TDG revision 2](https://grafana.com/api/dashboards/16405/revisions/2/download), [Prometheus TDG revision 2](https://grafana.com/api/dashboards/16406/revisions/2/download).
Fixed:
- TDG dashboard file connectors processed panel name changed to
"Total files processed"
- Set valid metrics name to TDG dashboard Kafka partitions panels
- Display only 99th quantile for Prometheus TDG Kafka metrics

Release 1.2.1

---

CHANGELOG.md
dashboard/influxdb_dashboard.libsonnet
dashboard/panels/expirationd.libsonnet
dashboard/prometheus_dashboard.libsonnet
dashboard/section.libsonnet
example_cluster/project/generate_load.lua
example_cluster/project/project-scm-1.rockspec
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Statistics for expirationd module was introduced in [expirationd 1.2.0](https://github.com/tarantool/expirationd/releases/tag/1.2.0). Statistics integrated with metrics and enabled by default.
To disable statistics integrated with metrics, call:
```Lua
expirationd.cfg({
metrics = false
})
```
This patch adds panels for counters:
- expirationd_checked_count
- expirationd_expired_count
- expirationd_restarts
- expirationd_working_time
The meaning of counters is same as for [expirationd.stats()](https://tarantool.github.io/expirationd/#stats).
expirationd panels are stored in "expirationd module statistics"
section. Mostly it [copy-paste](https://github.com/tarantool/grafana-dashboard/blob/0c623e0fae8e526976ed70da5e5f5a6640856275/dashboard/panels/tdg/expirationd.libsonnet) from [TDG's …

dashboard: add panels for expirationd module statistics

---

dashboard/panels/crud.libsonnet
dashboard/section.libsonnet
example_cluster/project/generate_load.lua
example_cluster/project/project-scm-1.rockspec
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

This patch is a code health patch that introduces two foldl calls
to build similar CRUD panels in cycle instead of copypaste.
CRUD 0.12.0 introduced insert_many, insert_object_many, replace_many,
replace_object_many, upsert_many, upsert_object_many operations and
corresponding metrics labels. This patch adds panels for them.
1. https://github.com/tarantool/crud/releases/tag/0.12.0
Closes #165

CRUD many panels

---

CHANGELOG.md
Makefile
README.md
dashboard/build/influxdb/dashboard.libsonnet
dashboard/build/influxdb/tdg_dashboard.libsonnet
dashboard/build/prometheus/dashboard.libsonnet
dashboard/build/prometheus/tdg_dashboard.libsonnet
doc/monitoring/grafana_dashboard.rst
example_cluster/prometheus/alerts.yml
example_cluster/prometheus/prometheus.localapp.yml
example_cluster/prometheus/prometheus.tdg.yml
example_cluster/prometheus/prometheus.yml
example_cluster/prometheus/test_alerts.yml
example_cluster/telegraf/telegraf.conf
example_cluster/telegraf/telegraf.localapp.conf
example_cluster/telegraf/telegraf.tdg.conf
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_static.sh
tests/InfluxDB/dashboard_static_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_tdg_static.sh
tests/InfluxDB/dashboard_tdg_static_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_static.sh
tests/Prometheus/dashboard_static_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_static.sh
tests/Prometheus/dashboard_tdg_static_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Set default Prometheus job to `tarantool`. After this patch, it will be possible to import dashboard with `community.ansible.ansible_dashboard`, if Prometheus is configured to collect Tarantool metrics with
tarantool` job.
This patch also changes all examples job names to `tarantool`.
Set default InfluxDB measurement to `tarantool_http`. After this patch, it will be possible to import dashboard with
`community.ansible.ansible_dashboard`, if Telegraf is configured to collect Tarantool metrics with `http` plugin and `tarantool_` prefix.
This patch also changes all examples measurement names to `tarantool_http`.
Closes #138

Dashboard defaults

---

CHANGELOG.md
dashboard/panels/runtime.libsonnet
dashboard/section.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_static_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_tdg_static_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_static_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_static_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Merge after #169 
Add "Runtime arena memory" panel to "Tarantool runtime overview" section. It displays `tnt_runtime_used` default metric.
Rename "Lua runtime memory" panel to "Lua memory" to not confuse users after adding "Runtime arena memory" panel. Update panel description so it would be easier to understand the differences between two panels.
Closes #140

dashboard: add runtime arena memory panel

---

CHANGELOG.md
dashboard/panels/vinyl.libsonnet
dashboard/section.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_static_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_tdg_static_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_compiled.json
tests/Prometheus/dashboard_static_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_static_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

Merge after #170
Before this patch, the code had `tnt_vinyl_memory_tuple_cache` and `tnt_vinyl_memory_level0` panels, but they weren't added to any dashboard. This patch fixes this behavior and adds "Tuples cache memory" and "Level 0 memory" panels to vinyl section.
Closes #154

Add vinyl memory panels

---

CHANGELOG.md
dashboard/panels/cluster.libsonnet
dashboard/panels/common.libsonnet
dashboard/panels/crud.libsonnet
dashboard/panels/expirationd.libsonnet
dashboard/panels/http.libsonnet
dashboard/panels/operations.libsonnet
dashboard/panels/space.libsonnet
dashboard/panels/tdg/expirationd.libsonnet
dashboard/panels/tdg/file_connectors.libsonnet
dashboard/panels/tdg/graphql.libsonnet
dashboard/panels/tdg/iproto.libsonnet
dashboard/panels/tdg/kafka/brokers.libsonnet
dashboard/panels/tdg/kafka/topics.libsonnet
dashboard/panels/tdg/kafka/utils.libsonnet
dashboard/panels/tdg/rest_api.libsonnet
dashboard/panels/tdg/tasks.libsonnet
dashboard/panels/tdg/tuples.libsonnet
dashboard/panels/vinyl.libsonnet
tests/InfluxDB/dashboard_compiled.json
tests/InfluxDB/dashboard_static_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_tdg_static_compiled.json
tests/InfluxDB/dashboard_with_custom_panels.jsonnet
tests/InfluxDB/dashboard_with_custom_panels_compiled.json

This patch replaces fill(none) with fill(null) in dashboards InfluxQL requests. After this patch, all panels with non-derivative requests will show the gap in metrics for an interval if there were no metrics for this interval. Before this patch, they had displayed a straight line connecting border values in the area. Derivative requests will still display a straight line [1]. There is a workaround to make derivative requests result consistent with non-derivative one, but it makes query more complicated both in terms of readability and performance, so it's not worth it.
1. https://github.com/influxdata/influxdb/issues/7185
Closes #23

dashboard: use fill(null) in InfluxQL requests

---

doc/monitoring/alerting.rst
doc/monitoring/grafana_dashboard.rst
example_cluster/prometheus/alerts.yml
example_cluster/prometheus/test_alerts.yml

Should be merged together with https://github.com/tarantool/metrics/pull/394
This PR introduces "Alerting" documentation page to a "Monitoring" section. Contents are based on this repo [``alerts.yml``](https://github.com/tarantool/grafana-dashboard/blob/8a11235e5a2293d271b1a60feb351c6107e64364/example_cluster/prometheus/alerts.yml) example file and are expected to be updated together with it.
This PR also introduces several minor fixes and reworks in example alert file.
This PR also fixes links in another documentation page: [``grafana_dashboard.rst``](https://github.com/tarantool/grafana-dashboard/blob/8a11235e5a2293d271b1a60feb351c6107e64364/doc/monitoring/grafana_dashboard.rst). The issue was found while working on "Alerting" page.
See commit comments for more details.
Closes #64

Alerting documentation

---

CHANGELOG.md
dashboard/panels/tdg/graphql.libsonnet
dashboard/panels/tdg/iproto.libsonnet
dashboard/panels/tdg/rest_api.libsonnet
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_tdg_static_compiled.json
tests/InfluxDB/dashboard_tdg_static_custom_title_compiled.json
tests/InfluxDB/dashboard_tdg_static_with_instance_variable_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_tdg_static_compiled.json
tests/Prometheus/dashboard_tdg_static_custom_title_compiled.json
tests/Prometheus/dashboard_tdg_static_with_instance_variable_compiled.json

Fix latency units for GraphQL [1], IProto [2] and REST API [3] panels.
1. https://github.com/tarantool/tdg2/blob/b283c91e17fec274d1be187fb734418a7f56a034/common/graphql.lua#L633
2. https://github.com/tarantool/tdg2/blob/7983a6a7b149ac2e9e94e052d01513076847bdff/input_processor/model_iproto.lua#L57
3. https://github.com/tarantool/tdg2/blob/98b113eb4a4f71f26a34f2522e6a93ed4e67db90/input_processor/model_rest.lua#L393
Closes #190
If this pull request introduces support for new metrics, do not forget to
- add Grafana panel;
- add example application code to generate non-null metrics;
- attach a screenshot of a new panel to the PR description;
- add new Telegraf tag key, if relevant,
- to all `telegraf.conf` files,
- to "Grafana dashboard" documentation page;
- add alert example, if relevant,
- …

tdg_dashboard: fix latency units

---

supported_metrics.md

Update list of supported metrics based on new modules versions.
Part of #164
Part of #176
Part of #178
Part of #197
If this pull request introduces support for new metrics, do not forget to
- add Grafana panel;
- run `make update-tests` to build new dashboard artifacts;
- add example application code to generate non-null metrics;
- attach a screenshot of a new panel to the PR description;
- add new Telegraf tag key, if relevant,
- to all `telegraf.conf` files,
- to "Grafana dashboard" documentation page;
- add alert example, if relevant,
- to `alerts.yml`,
- to "Alerting" documentation page;
In any case, do not forget to
- add a CHANGELOG entry;
- update documentation guidelines;
- update README guidelines.

doc: update list of supported metrics

---

CHANGELOG.md

Grafana revisions:
- InfluxDB revision 16 [1],
- Prometheus revision 16 [2],
- InfluxDB TDG revision 5 [3],
- Prometheus TDG revision 5 [4].
Added:
- Dashboard title customization
- Panels for transaction operations
- Panels with net statistics per thread
- Panel with failover trigger count
- Panels with syncro replication queue statistics
- Panels with leader election statistics
- Panels with MVCC statistics
Changed:
- Replace LuaJit deprecated metrics with new ones
- Set Prometheus `job` dynamically
- Set InfluxDB `measurement` dynamically
- Set InfluxDB `policy` dynamically
- Set datasource dynamically
- Use expirationd module metrics in TDG dashboard
- Move replication panels to a separate row
Fixed:
- TDG dashboard latency units (graphql, iproto, rest requests)
1. …

release: 2.0.0

---

CHANGELOG.md
dashboard/panels/common.libsonnet
dashboard/panels/tdg/graphql.libsonnet
dashboard/panels/tdg/tasks.libsonnet
dashboard/panels/tdg/tuples.libsonnet
docker-compose.cartridge.yml
docker-compose.tdg.yml
docker-compose.yml
tests/InfluxDB/dashboard_cartridge_compiled.json
tests/InfluxDB/dashboard_custom_compiled.json
tests/InfluxDB/dashboard_tarantool3_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_with_custom_panels.jsonnet
tests/InfluxDB/dashboard_with_custom_panels_compiled.json

On lower timescales data with `fill(null)` seems like a scattered set of dots. Data with `fill(none)` seems fine like a line string. I don't remember these issues on older Grafana versions, so it is possible that something had changed with visualization even for deprecated graph panels.

dashboard: fill with none for InfluxDB

---

CHANGELOG.md
dashboard/build/dashboard.libsonnet
dashboard/panels/cluster.libsonnet
docker-compose.cartridge.yml
docker-compose.localapp.yml
docker-compose.tdg.yml
docker-compose.yml
example_cluster/tarantool3_project/app.Dockerfile
tests/InfluxDB/dashboard_cartridge_compiled.json
tests/InfluxDB/dashboard_custom_compiled.json
tests/InfluxDB/dashboard_tarantool3_compiled.json
tests/InfluxDB/dashboard_tdg_compiled.json
tests/InfluxDB/dashboard_with_custom_panels_compiled.json
tests/Prometheus/dashboard_cartridge_compiled.json
tests/Prometheus/dashboard_custom_compiled.json
tests/Prometheus/dashboard_tarantool3_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json
tests/Prometheus/dashboard_with_custom_panels_compiled.json

grafonnet doesn't fill up empty thresholds for hidden fields. After table code rework introduced in Grafana 11, empty thresholds result in panel crush.
Thanks to @0x501D for exploring the issue.
Closes #234
Before this patch, older Grafana 6 color scheme were used for overview panel. It was fine for Grafana from 8 to 10, but don't work properly with Grafana 11 [Figure 1]. After this patch, the panel works properly with Grafana 11 and newer  [Figure 2]. For Grafana 9 and 10 everything works fine, except for row coloring: only single cell is colored [1,  Figure 3]. For Grafana 8 and older, table column hiding no longer works properly so it's simpler for us to treat it as unsupported since it's EOLed 1 year and 3 months ago [2,  Figure 4].
1. https://github.com/grafana/grafana/issues/27542 …

dashboard: fix cluster overview for Grafana 11

---

CHANGELOG.md

Grafana revisions
- Tarantool 3:
- Prometheus revision 5 [1],
- InfluxDB revision 5 [2];
- Tarantool Cartridge and 1.10—2.x:
- Prometheus revision 21 [3],
- InfluxDB revision 21 [4];
- Tarantool Data Grid 2:
- Prometheus revision 10 [5],
- InfluxDB revision 10 [6].
- Use Grafana 11 color scheme for Prometheus cluster overview panel (#234)
- Drop Grafana 8 support (#234)
- Bump recommended requirements to Grafana 11 (#234)
- Prometheus cluster overview panel not works for Grafana 11+ (#234)
1. https://grafana.com/api/dashboards/21474/revisions/5/download
2. https://grafana.com/api/dashboards/21484/revisions/5/download
3. https://grafana.com/api/dashboards/13054/revisions/21/download
4. https://grafana.com/api/dashboards/12567/revisions/21/download
5. …

dashboard: release 3.2.0

---

CHANGELOG.md
dashboard/panels/tdg/graphql.libsonnet
dashboard/panels/tdg/tasks.libsonnet
dashboard/panels/tdg/tuples.libsonnet
tests/Prometheus/dashboard_tdg_compiled.json

Before this patch, Prometheus average panels (histogram or summary `metric_sum / metric_count`) were displaying instance runtime average info. This info is rather useless since, in case of instance lifetime being longer than several dozens of metrics collect intervals (which happens often), computed average becomes almost constant. Prometheus itself advises to use moving average for this.
Before (customer screenshot):
After (customer screenshot):
InfluxDB panels already implement moving averages, so there's no need to update them.
1. https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations
Closes #237

dashboard: fix Prometheus TDG moving average

---

CHANGELOG.md

Grafana revisions:
- Tarantool 3:
- [Prometheus revision 5](https://grafana.com/api/dashboards/21474/revisions/5/download),
- [InfluxDB revision 5](https://grafana.com/api/dashboards/21484/revisions/5/download);
- Tarantool Cartridge and 1.10—2.x:
- [Prometheus revision 21](https://grafana.com/api/dashboards/13054/revisions/21/download),
- [InfluxDB revision 21](https://grafana.com/api/dashboards/12567/revisions/21/download);
- Tarantool Data Grid 2:
- [Prometheus revision 11](https://grafana.com/api/dashboards/16406/revisions/11/download),
- [InfluxDB revision 11](https://grafana.com/api/dashboards/16405/revisions/11/download).
- Prometheus TDG average panels displaying lifetime average instead of a moving one (#237)

dashboard: release 3.2.1

---

CHANGELOG.md
dashboard/panels/cluster.libsonnet
dashboard/section.libsonnet
supported_metrics.md
tests/Prometheus/dashboard_cartridge_compiled.json
tests/Prometheus/dashboard_tdg_compiled.json

Replace "Config application status" panel with "Configuration checksum" panel (https://github.com/tarantool/metrics/pull/516).
Closes TNTP-2845
If this pull request introduces support for new metrics, do not forget to
In any case, do not forget to

dashboard: replace config application status panel with config checksum panel
